### ISSUE TITLE
Custom port for moodole apache

### ISSUE THREAD

**Issue by empeje** [treehouses/moodole#38]
Custom port for moodole apache

**Comment by empeje** [comment]
No need to change anything, just edit this `docker-compose-ready.yml`
```
version: '2'
services:
  moodledb:
    image: postgres
    container_name: moodledb
    environment:
    # MAKE SURE THIS ONE SAME WITH THE MOODLE
    - POSTGRES_DATABASE=moodle
    - POSTGRES_USER=moodle
    - POSTGRES_PASSWORD=moodle
  moodle:
    image: treehouses/moodle:apache-latest
    container_name: moodle
    ports:
      - "8123:80"
    environment:
    - MOODOLE_DB_URL=moodledb
    - MOODOLE_DB_NAME=moodle
    - MOODOLE_DB_USER=moodle
    - MOODOLE_DB_PASS=moodle
    - MOODOLE_DB_PORT=5432
    - MOODOLE_POST_MAX_SIZE=200M
    - MOODOLE_UPLOAD_MAX_FILESIZE=200M
```
It works like a charm 
<img width="1280" alt="screen shot 2018-02-15 at 6 35 14 pm" src="https://user-images.githubusercontent.com/11813607/36254824-1c3e2a3c-127f-11e8-82e3-316274747f49.png">
