### ISSUE TITLE
http was not build unclean shutdown

### ISSUE THREAD

**Issue by empeje** [treehouses/moodole#7]
only the DB start on next boot
when I do docker logs of moodle

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this messag
e 
httpd (pid 1) already running
```

https://askubuntu.com/questions/256013/apache-error-could-not-reliably-determine-the-servers-fully-qualified-domain-n

quick fix

```
found the bug
and did a quick fix
cat /boot/autorun  
#!/bin/sh                                                                                                                                      
                                                                                                                                                           
sleep 1                                                                                                                                                     
docker start ole 

sleep 2 
rm -rf /home/pi/apache2 
mkdir -p /home/pi/apache2 
docker-compose -f /home/pi/moodole3.yml -p moodole3 start 

node /root/ole/server.js
```

AND

```
cat /home/pi/moodole3.yml  
moodledb_rpi3: 
 image: arm32v7/postgres 
 container_name: moodledb_rpi3 
 ports: 
   - "5432:5432" 
 environment: 
   - POSTGRES_DATABASE=moodle 
   - POSTGRES_USER=moodle 
   - POSTGRES_PASSWORD=moodle 
moodle_rpi3: 
 image: treehouses/moodle:arm 
 container_name: moodle_rpi3
 ports: 
   - "8080:80" 
 links: 
   - moodledb_rpi3 
 volumes: 
   - /home/pi/apache2:/var/run/apache2 
 environment: 
   - MOODLE_URL=http://docker.ole.org:80
```
